### ISSUE TITLE
Multi-line descriptions break listing tables

### ISSUE THREAD

**Issue by KillyMXI** [godaddy/dmd#5]
Command line I'm using: `jsdoc2md --plugin @godaddy/dmd -f lib/typedefs.js > API.md`

Example 1. Typedef description consists of two lines split by empty line. This syntax is recognized by every other tool I know.

```javascript
/**
 * @typedef { object } Foo
 * Foo line one.
 *
 * Foo line two.
 *
 * @property { boolean } [bar = false]
 * Bar description.
 *
 * @property { boolean } [baz = false]
 * Baz description.
 */
```

Example 2. Typedef description consists of two lines with linebreak escape. This syntax is recognized by VSCode.

```javascript
/**
 * @typedef { object } Foo
 * Foo line one. \
 * Foo line two.
 *
 * @property { boolean } [bar = false]
 * Bar description.
 *
 * @property { boolean } [baz = false]
 * Baz description.
 */
```

While in other tables newlines are removed completely *(I wish there were a way to choose a behavior though - I want as little html as possible, but I also can tolerate `<br/>` where it makes sense)*, listings at the top of document behave differently.

`Typedefs` - description transferred to markdown output as-is in both cases, breaking the table formatting.

```
## Typedefs

Name | Description
------ | -----------
[Foo] | Foo line one.

Foo line two.
```

```
## Typedefs

Name | Description
------ | -----------
[Foo] | Foo line one. \
Foo line two.
```

`Functions` - with the first style description only uses the first line, with the second style description - removes newline but leaves escape symbol behind.

```
## Functions

Name | Description
------ | -----------
[foo1(bar, \[baz\])] | Foo line one.
[foo2(bar, \[baz\])] | Foo line one. \ Foo line two.
```

**Comment by kinetifex** [comment]
@KillyMXI thanks for reporting! I added a fix and some docs to clarify expected behavior for the index tables over in #7
